# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import caffe_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='video_shot_sentences.proto',
  package='video_shot_sentences',
  serialized_pb='\n\x1avideo_shot_sentences.proto\x12\x14video_shot_sentences\x1a\x0b\x63\x61\x66\x66\x65.proto\"\x9a\x01\n\x0fVideoShotWindow\x12\x10\n\x08video_id\x18\x01 \x01(\x05\x12\x0f\n\x07shot_id\x18\x02 \x01(\x05\x12\x12\n\nvideo_name\x18\x03 \x01(\t\x12&\n\x10target_shot_word\x18\x04 \x01(\x0b\x32\x0c.caffe.Datum\x12(\n\x12\x63ontext_shot_words\x18\x05 \x03(\x0b\x32\x0c.caffe.Datum')




_VIDEOSHOTWINDOW = descriptor.Descriptor(
  name='VideoShotWindow',
  full_name='video_shot_sentences.VideoShotWindow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='video_id', full_name='video_shot_sentences.VideoShotWindow.video_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shot_id', full_name='video_shot_sentences.VideoShotWindow.shot_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='video_name', full_name='video_shot_sentences.VideoShotWindow.video_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_shot_word', full_name='video_shot_sentences.VideoShotWindow.target_shot_word', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='context_shot_words', full_name='video_shot_sentences.VideoShotWindow.context_shot_words', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=220,
)

_VIDEOSHOTWINDOW.fields_by_name['target_shot_word'].message_type = caffe_pb2._DATUM
_VIDEOSHOTWINDOW.fields_by_name['context_shot_words'].message_type = caffe_pb2._DATUM
DESCRIPTOR.message_types_by_name['VideoShotWindow'] = _VIDEOSHOTWINDOW

class VideoShotWindow(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VIDEOSHOTWINDOW
  
  # @@protoc_insertion_point(class_scope:video_shot_sentences.VideoShotWindow)

# @@protoc_insertion_point(module_scope)
